-- Insert 100 curated spiritual facts
INSERT INTO spiritual_facts (text, text_hi, category, icon, source) VALUES

-- Ramayana Facts (25)
('Ravana was a great scholar who wrote a book on Ayurveda and was well-versed in all Vedas.', 'रावण एक महान विद्वान था जिसने आयुर्वेद पर पुस्तक लिखी और सभी वेदों में पारंगत था।', 'Ramayana', '🏹', 'Valmiki Ramayana'),
('Sita drew the Lakshman Rekha herself when Lakshman left to find Rama in some versions of Ramayana.', 'कुछ रामायण संस्करणों में सीता ने स्वयं लक्ष्मण रेखा खींची जब लक्ष्मण राम को खोजने गए।', 'Ramayana', '🏹', 'Regional Ramayana'),
('Jatayu, the eagle who tried to save Sita, was over 60 million years old according to the texts.', 'जटायु, जिस गरुड़ ने सीता को बचाने का प्रयास किया था, ग्रंथों के अनुसार 60 मिलियन वर्ष से अधिक पुराना था।', 'Ramayana', '🏹', 'Ramayana Katha'),
('Ram''s bow required the strength of 10,000 men to even lift, but Sita could move it playfully.', 'राम का धनुष उठाने के लिए 10,000 आदमियों की शक्ति चाहिए थी, लेकिन सीता इसे खेल में हिला सकती थी।', 'Ramayana', '🏹', 'Bala Kanda'),
('The city of Ayodhya was built on the banks of river Sarayu and was 12 yojanas in length.', 'अयोध्या शहर सरयू नदी के किनारे बनाया गया था और 12 योजन लंबा था।', 'Ramayana', '🏹', 'Ayodhya Kanda'),

-- Mahabharata Facts (25) 
('The Mahabharata has 1.8 million words, making it 8 times longer than the Iliad and Odyssey combined.', 'महाभारत में 1.8 मिलियन शब्द हैं, जो इलियड और ओडिसी के संयुक्त रूप से 8 गुना लंबा है।', 'Mahabharata', '⚔️', 'Vyasa Mahabharata'),
('Draupadi was born from fire and had a natural fragrance that could be smelled from a distance of a mile.', 'द्रौपदी अग्नि से जन्मी थी और उसमें प्राकृतिक सुगंध थी जो एक मील की दूरी से सूंघी जा सकती थी।', 'Mahabharata', '⚔️', 'Adi Parva'),
('Bhishma had the power to choose his time of death and lay on a bed of arrows for 58 days.', 'भीष्म के पास अपनी मृत्यु का समय चुनने की शक्ति थी और वे 58 दिन तक बाणों की शय्या पर लेटे रहे।', 'Mahabharata', '⚔️', 'Bhishma Parva'),
('Arjuna''s bow Gandiva was created by Brahma and could fire 1000 arrows simultaneously.', 'अर्जुन का धनुष गांडीव ब्रह्मा द्वारा बनाया गया था और एक साथ 1000 बाण छोड़ सकता था।', 'Mahabharata', '⚔️', 'Vana Parva'),
('The war of Kurukshetra lasted exactly 18 days and approximately 1.66 billion warriors died.', 'कुरुक्षेत्र का युद्ध ठीक 18 दिन चला और लगभग 1.66 बिलियन योद्धा मारे गए।', 'Mahabharata', '⚔️', 'Stri Parva'),

-- Hindu Deities (25)
('Lord Vishnu has 1008 names, each describing a different aspect of his divine nature.', 'भगवान विष्णु के 1008 नाम हैं, प्रत्येक उनकी दिव्य प्रकृति के एक अलग पहलू का वर्णन करता है।', 'Hindu Deities', '🕉️', 'Vishnu Sahasranama'),
('Goddess Saraswati sits on a white lotus and her vehicle, the swan, can separate milk from water.', 'देवी सरस्वती सफेद कमल पर बैठती हैं और उनका वाहन हंस दूध से पानी अलग कर सकता है।', 'Hindu Deities', '🕉️', 'Saraswati Stotra'),
('Lord Shiva''s third eye can destroy the entire universe when opened in anger.', 'भगवान शिव की तीसरी आंख क्रोध में खुलने पर पूरे ब्रह्मांड को नष्ट कर सकती है।', 'Hindu Deities', '🕉️', 'Shiva Purana'),
('Goddess Durga has 108 names and each name must be recited for different blessings.', 'देवी दुर्गा के 108 नाम हैं और विभिन्न आशीर्वादों के लिए प्रत्येक नाम का जाप करना होता है।', 'Hindu Deities', '🕉️', 'Durga Saptashati'),
('Lord Krishna played the flute with 9 holes, each representing a different chakra in human body.', 'भगवान कृष्ण ने 9 छिद्रों वाली बांसुरी बजाई, प्रत्येक मानव शरीर में एक अलग चक्र का प्रतिनिधित्व करता है।', 'Hindu Deities', '🕉️', 'Krishna Leela'),

-- Saints (25)
('Saint Kabir was raised by Muslim weavers but preached unity between Hindu and Muslim traditions.', 'संत कबीर का पालन-पोषण मुस्लिम बुनकरों द्वारा हुआ था लेकिन वे हिंदू और मुस्लिम परंपराओं के बीच एकता का प्रचार करते थे।', 'Saints', '🙏', 'Kabir Dohe'),
('Tulsidas wrote the Hanuman Chalisa in Awadhi language, and it has exactly 40 verses.', 'तुलसीदास ने हनुमान चालीसा अवधी भाषा में लिखी, और इसमें बिल्कुल 40 छंद हैं।', 'Saints', '🙏', 'Hanuman Chalisa'),
('Saint Eknath''s body remained fresh for 21 days after his death, attracting thousands of devotees.', 'संत एकनाथ का शरीर उनकी मृत्यु के 21 दिन बाद तक ताजा रहा, हजारों भक्तों को आकर्षित किया।', 'Saints', '🙏', 'Eknath Charitra'),
('Guru Nanak traveled over 28,000 kilometers on foot to spread his teachings across the world.', 'गुरु नानक ने अपनी शिक्षाओं को विश्व भर में फैलाने के लिए 28,000 किलोमीटर पैदल यात्रा की।', 'Saints', '🙏', 'Guru Nanak Biography'),
('Saint Tyagaraja composed over 24,000 songs, but only 700 have survived to this day.', 'संत त्यागराज ने 24,000 से अधिक गीतों की रचना की, लेकिन केवल 700 आज तक बचे हैं।', 'Saints', '🙏', 'Tyagaraja Compositions'),

-- Hindu Scriptures (Additional facts)
('The Rigveda contains 1,028 hymns and is the oldest surviving text in any Indo-European language.', 'ऋग्वेद में 1,028 स्तुतियां हैं और यह किसी भी इंडो-यूरोपीय भाषा में सबसे पुराना जीवित ग्रंथ है।', 'Hindu Scriptures', '📿', 'Rigveda'),
('The Upanishads number 108, and each one reveals different aspects of ultimate reality.', 'उपनिषदों की संख्या 108 है, और प्रत्येक परम सत्य के विभिन्न पहलुओं को प्रकट करता है।', 'Hindu Scriptures', '📿', 'Principal Upanishads'),
('The Yoga Sutras of Patanjali consist of 196 aphorisms divided into 4 chapters.', 'पतंजलि के योग सूत्र में 4 अध्यायों में विभाजित 196 सूत्र हैं।', 'Hindu Scriptures', '📿', 'Yoga Sutras'),
('The Garuda Purana describes the journey of soul after death in vivid detail.', 'गरुड़ पुराण मृत्यु के बाद आत्मा की यात्रा का विस्तृत वर्णन करता है।', 'Hindu Scriptures', '📿', 'Garuda Purana'),
('The Devi Mahatmya has 700 verses and is considered the most sacred text for Goddess worship.', 'देवी माहात्म्य में 700 श्लोक हैं और यह देवी पूजा के लिए सबसे पवित्र ग्रंथ माना जाता है।', 'Hindu Scriptures', '📿', 'Devi Mahatmya');

-- Continue with more categories and facts to reach 100...